name: Sync Environment Variables

on:
  push:
    paths:
      - '.env'

jobs:
  update-testB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository A
        uses: actions/checkout@v2

      - name: Extract TEST_A variable
        run: |
          echo "TEST_A=$(grep 'TEST_A' .env | cut -d '=' -f2)" >> $GITHUB_ENV

      - name: Update TEST_B in Repository B
        env:
          REPO_B_PAT: ${{ secrets.REPO_B_PAT }}
          TEST_A: ${{ env.TEST_A }}
        run: |
          curl -X PUT \
            -H "Authorization: token $REPO_B_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/diegodmitry/repo-b/actions/secrets/TEST_B \
            -d "{\"encrypted_value\":\"$(echo -n $TEST_A | base64)\"}"

